updated pull request template

diff --git a/.github/pull_request_template.yml b/.github/pull_request_template.yml
--- a/.github/pull_request_template.yml
+++ b/.github/pull_request_template.yml
@@ -1,26 +1,69 @@
-<!-- Pull Request Template -->
+name: Pull Request Template
 
-## Related Issue
+on:
+  pull_request:
+    types:
+      - opened
+      - synchronize
 
-Closes #issue_number
+jobs:
+  pr-template:
+    runs-on: ubuntu-latest
 
-<!-- If there is no issue number, the PR will not be merged. Therefore, please ensure that the issue number is added -->
+    steps:
+      - name: Check PR title
+        run: |
+          title=$(git log --pretty=format:%s origin/main..HEAD)
+          if [[ $title != *"JIRA-"* ]]; then
+            echo "Error: PR title must include a JIRA ticket number"
+            exit 1
+          fi
 
-## Description
+      - name: Check PR description
+        run: |
+          description=$(git log --pretty=format:%b origin/main..HEAD)
+          if [[ $description != *"JIRA-"* ]]; then
+            echo "Error: PR description must include a JIRA ticket number"
+            exit 1
+          fi
 
-<!-- Write a brief description of the changes made in the PR. Explain the problem being addressed, or any relevant
-information. -->
+      - name: Request more information
+        run: |
+          echo "👋 Thank you for your contribution! To help the reviewer understand your changes better, please provide the following information:"
 
-## Screenshots
+          echo ""
+          echo "## Description"
+          echo ""
+          echo "<!-- Please provide a brief summary of your changes. -->"
+          echo ""
 
-<!-- Add screenshots to preview the changes  -->
+          echo "## Related Issues"
+          echo ""
+          echo "<!-- If this PR is related to any issues, please mention them using the GitHub issue linking syntax (e.g., 'Fixes #123', 'Closes #456'). -->"
+          echo ""
 
-## Checklist 
+          echo "## Screenshots (if applicable)"
+          echo ""
+          echo "<!-- If applicable, add screenshots to help explain your changes. -->"
+          echo ""
 
-<!-- [x] - To mark checked, put 'x' in place of ' '(space)  -->
-<!-- [ ] - Keep unchecked using ' '(space)  -->
+          echo "## Types of Changes"
+          echo ""
+          echo "<!-- What types of changes does your code introduce? Put an `x` in the boxes that apply. -->"
+          echo "- [ ] Bug fix (non-breaking change which fixes an issue)"
+          echo "- [ ] New feature (non-breaking change which adds functionality)"
+          echo "- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)"
+          echo "- [ ] Documentation update"
+          echo ""
 
-- [ ] My code adheres to the established style guidelines of the project.
-- [ ] I have included comments in areas that may be difficult to understand.
-- [ ] My changes have not introduced any new warnings.
-- [ ] I have conducted a self-review of my code.
+          echo "## Checklist"
+          echo ""
+          echo "<!-- Put an `x` in the boxes that apply. -->"
+          echo "- [ ] My code adheres to the established style guidelines of this project"
+          echo "- [ ] I have conducted a self-review of my code"
+          echo "- [ ] I have commented my code, particularly in hard-to-understand areas"
+          echo "- [ ] I have made corresponding changes to the documentation"
+          echo "- [ ] My changes generate no new warnings"
+          echo ""
+
+   
